pipeline {
	agent none

	stages {
		stage('build'){
			agent {
				docker {
					image 'python:2.7.16-slim'
					args '--user root'
				}
			}
			when {
				changeset '**/vote/**'
			}
			steps {
				echo 'Building Vote Python APP'
				dir('vote'){
					sh 'pip install -r requirements.txt'
				}
			}
		}

		stage('test'){
			agent {
				docker {
					image 'python:2.7.16-slim'
					args '--user root'
				}
			}
			when {
				changeset '**/vote/**'
			}
			steps {
				echo 'Unit Testing for Python APP'
				dir('vote'){
					sh 'pip install -r requirements.txt'
					sh 'nosetests -v'
				}
			}
		}
		
		stage('package'){
			agent any
			when {
				changeset '**/vote/**'
				branch 'master'
			}
			steps {
				echo "Packaging Vote App with Docker Image Build"
				script {
					docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
						def vote_image = docker.build("vote:v${env.BUILD_ID}", "./vote")
						vote_image.push()
						vote_image.push('latest')
					}
				}
			}
		}
	}
} 
