pipeline {
	agent {
		docker {
			image 'python:2.7.16-slim'
			args '--user root'
		}
	}

	stages {
		stage('build'){
			when {
				changeset '**/vote/**'
			}
			steps {
				echo 'Building Vote Python APP'
				dir('vote'){
					sh 'pip install -r requirements.txt'
				}
			}
		}

		stage('test'){
			when {
				changeset '**/vote/**'
			}
			steps {
				echo 'Unit Testing for Python APP'
				dir('vote'){
					sh 'nosetests -v'
				}
			}
		}
		
		stage('package'){
			when {
				changeset '**/vote/**'
			}
			steps {
				echo "Packaging Vote App with Docker Image Build"
				script {
					docker.build("vote:v${env.BUILD_ID}", "./vote")
				}
			}
		}
	}
} 
